# Generated by Django 5.0.6 on 2025-03-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets_Respusetas_Automaticas',
            new_name='Tickets_Respuestas_Automaticas',
        ),
    ]
