# Generated by Django 5.0.6 on 2025-03-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0002_rename_tickets_respusetas_automaticas_tickets_respuestas_automaticas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets_respuestas_automaticas',
            name='descripcion',
        ),
    ]
