# Generated by Django 5.0.6 on 2025-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0003_remove_tickets_respuestas_automaticas_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentes',
            name='telefono',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
