# Generated by Django 5.0.6 on 2025-03-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0006_agentes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentes_por_grupos',
            name='agente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agente', to='tikects_app.agentes'),
        ),
    ]
