# Generated by Django 5.0.6 on 2025-03-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0007_alter_agentes_por_grupos_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentes_por_grupos',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.agentes'),
        ),
    ]
