# Generated by Django 5.0.6 on 2025-03-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0009_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='gerencia',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
