# Generated by Django 5.0.6 on 2025-03-04 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0012_tickets_gerencia_tickets_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTikects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_reasignacion', models.IntegerField()),
                ('agente_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente_actual', to='tikects_app.agentes')),
                ('agente_reasignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_reasignacion', to='tikects_app.agentes')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets_servicios')),
            ],
        ),
    ]
