# Generated by Django 5.0.6 on 2025-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0013_asignaciontikects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontikects',
            name='tiempo_reasignacion',
            field=models.IntegerField(null=True),
        ),
    ]
