# Generated by Django 5.0.6 on 2025-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0014_alter_asignaciontikects_tiempo_reasignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciontikects',
            name='tiempo_reasignacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
