# Generated by Django 5.0.6 on 2025-03-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0015_alter_asignaciontikects_tiempo_reasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='cerrado_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
