# Generated by Django 5.0.6 on 2025-03-06 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0016_tickets_cerrado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentes',
            name='ultima_conexion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
