# Generated by Django 5.0.6 on 2025-03-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0017_agentes_ultima_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='descripcion_cierre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
