# Generated by Django 5.0.6 on 2025-03-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0018_tickets_descripcion_cierre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='descripcion_cierre',
            new_name='descripcion_solucion',
        ),
    ]
