# Generated by Django 5.0.6 on 2025-03-07 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0019_rename_descripcion_cierre_tickets_descripcion_solucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasignacionTikects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reasignacion', models.DateTimeField(auto_now_add=True)),
                ('agente_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_anterior', to='tikects_app.agentes')),
                ('agente_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_nuevo', to='tikects_app.agentes')),
                ('tikect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikects_app.tickets')),
            ],
        ),
    ]
