# Generated by Django 5.0.6 on 2025-03-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0022_alter_notificaciones_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
