# Generated by Django 5.0.6 on 2025-03-21 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikects_app', '0024_gerencias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='cerrado_por_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cerrado_por_agente', to=settings.AUTH_USER_MODEL),
        ),
    ]
